### ISSUE TITLE
question: epoll thread never wake up with `http_get_slow` removed

### ISSUE THREAD

**Issue by c00t** [cfsamson/book-exploring-async-basics#61]
With current impls, if I remove `Http::http_get_slow` from `javascript()` function, the epoll thread will be parked forever. because we handle timeout inside the epoll thread, some timers never fire.

I think it's a constraint from `minimio`, right? if I want to improve it, I should implement something like [Waker](https://docs.rs/mio/latest/x86_64-unknown-linux-gnu/mio/struct.Waker.html) in `mio`, then call `Waker::wake` periodly to wake up the epoll thread? or create a customed timer event instead?

**Comment by cfsamson** [comment]
Hmm...

You're right, we handle the timouts in the epoll thread (which, if memory serves me right, is the same as libuv does).

However, re-reading the code now there is a corner case if you have no calls that forces `poll` to return at least once by receiving some event, since we set the initial timeout to infinity. I don't think the error is with `minimio`. See:

```rust
let mut poll = minimio::Poll::new().expect("Error creating epoll queue");
let registrator = poll.registrator();
let epoll_timeout = Arc::new(Mutex::new(None)); // <---------- None = will never time out
let epoll_timeout_clone = epoll_timeout.clone();

let epoll_thread = thread::Builder::new()
    .name("epoll".to_string())
    .spawn(move || {
        let mut events = minimio::Events::with_capacity(1024);

        loop {
            let epoll_timeout_handle = epoll_timeout_clone.lock().unwrap();
            let timeout = *epoll_timeout_handle;
            drop(epoll_timeout_handle);

            match poll.poll(&mut events, timeout) { // <-------------- will possibly hang forever
                Ok(v) if v > 0 => {
                    for i in 0..v {
                        let event = events.get_mut(i).expect("No events in event list.");
                        print(format!("epoll event {} is ready", event.id()));

                        let event = PollEvent::Epoll(event.id());
                        event_sender.send(event).expect("epoll event");
                    }
                }
                Ok(v) if v == 0 => {
                    print("epoll event timeout is ready");
                    event_sender.send(PollEvent::Timeout).expect("epoll timeout");
                }
                Err(ref e) if e.kind() == io::ErrorKind::Interrupted => {
                    print("received event of type: Close");
                    break;
                }
                Err(e) => panic!("{:?}", e),
                _ => unreachable!(),
            }
        }
    })
    .expect("Error creating epoll thread");
```

I added some comments in to show where it probably goes wrong. Since we set the call to `poll` to wait forever on the first call, and only set the timeout to the next timer on the subsequent calls, it will not be able to handle timers in that case since the call most likely runs before the `javascript()` function is called and registers any timeouts.

One way to fix this (I think) is to set a default timeout:

Now, if we change:

```rust
let epoll_timeout = Arc::new(Mutex::new(None));
```

to:

```rust
let epoll_timeout = Arc::new(Mutex::new(1));
```

it should work and handle timers correctly.

There is probably a way to redesign this so the epoll thread doesn't loop needlessly and only calls epoll poll once it either have a I/O event or a timer it needs to wait for, but that is a little more involved.

You can also foce the epoll call to return by issuing a specific event through the kernel (I don't remember exactly how right now, but I know I implemented something like this when doing research) which let's the main thread force the epoll-thread to wake up and thereby check for timers and set the timeout accordingly. However, I didn't find a cross platform way fto do this, since I didn't find a way to force such a wakeup on Windows. I'm just mentioning this so you know there is another option there if you only use epoll on linux and doesn't need it to be cross platform.

**Comment by c00t** [comment]
Thanks for your explanation!
