### ISSUE TITLE
unclear/incorrect syscall instruction description

### ISSUE THREAD

**Issue by petr-matousek** [cfsamson/book-exploring-async-basics#63]
the paragraph in "[Communicating with the OS](https://cfsamson.github.io/book-exploring-async-basics/3_1_communicating_with_the_os.html)" section is not correct AFAICS.

"The syscall instruction is a rather new one. On the earlier 32-bit systems in the x86 architecture, you invoked a syscall by issuing a software interrupt int 0x80. A software interrupt is considered slow at the level we're working at here so later a separate instruction for it called syscall was added. The syscall instruction uses [VDSO](http://articles.manugarg.com/systemcallinlinux2_6.html), which is a memory page attached to each process' memory, so no context switch is necessary to execute the system call."

1) the syscall instruction does not use VDSO. VDSO is Linux specific so it would be weird for the syscall (CPU) instuction to be bound to one operating system. I think the confusion comes from the __kernel_vsyscall x86 32bit VDSO abstraction that is used to select the proper/most efficient syscall invocation method (int 0x80, sysenter, syscall (as in instruction)). 

2) context switch (as in userspace -> kernel switch) is necessary except for selected time and cpu related syscalls where VDSO provides a fast path. more info at https://man7.org/linux/man-pages/man7/vdso.7.html . since we're talking about write syscall, the context switch is definitely there.

sorry for nitpicking, I like your work! did not find any other way to contact you (looked for an email but failed), so here I am -)

**Comment by cfsamson** [comment]
Hi and thanks for reaching out and sorry for the long wait. Making an issue here is the right thing to do and thanks for making the effort :)

So, that paragraph was meant as sort of a "fun fact" but it seems to be plain out wrong as you've pointed out. `syscall` is supposedly faster on newer CPU's but it has nothing to do with VDSO, and I'm not sure how I got that idea. I'll correct this ASAP. 

And yes, a context switch (userspace -> kernel) is needed here.

Thanks for pointing it out, it's been a long time since I've re-read that part.

**Comment by petr-matousek** [comment]
thank you, Carl!
